def get_nse_symbols():
    return [
        # Core large caps / Nifty-heavy
        "RELIANCE",
        "TCS",
        "INFY",
        "HDFCBANK",
        "ICICIBANK",
        "SBIN",
        "LT",
        "ITC",
        "WIPRO",
        "AXISBANK",
        "KOTAKBANK",
        "HCLTECH",
        "BHARTIARTL",
        "BAJFINANCE",
        "ASIANPAINT",
        "MARUTI",
        "SUNPHARMA",
        "ULTRACEMCO",
        "TITAN",
        "POWERGRID",
        "NTPC",
        "ONGC",
        "TATAMOTORS",
        "M&M",
        "HINDUNILVR",
        "TECHM",
        "ADANIPORTS",
        "BAJAJFINSV",
        "NESTLEIND",
        "JSWSTEEL",

        # Bank Nifty related banks
        "AUBANK",
        "BANDHANBNK",
        "BANKBARODA",
        "CANBK",
        "FEDERALBNK",
        "IDFCFIRSTB",
        "INDUSINDBK",
        "PNB",

        # Higher-beta / midcaps
        "BHEL",
        "SAIL",
        "IDBI",
        "SUZLON",
        "YESBANK",
        "NHPC",
        "IREDA",
        "IRFC",
        "RVNL",
        "NBCC",
    ]